### ISSUE TITLE
Error when use meme function

### ISSUE THREAD

**Issue by xaryow** [Fredwuz/venom-bot-WhatsappWebBot#1]
This error show when i try to use meme function 

internal/streams/legacy.js:61
      throw er; // Unhandled stream error in pipe.
      ^

[Error: ENOENT: no such file or directory, open '/home/pi/whatsappweb/bilder/xhtnnc2ahue51.jpg'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/pi/whatsappweb/bilder/xhtnnc2ahue51.jpg'
}

**Comment by Fredwuz** [comment]
ehh yeah sry for that you have to change "/home/pi/whatsappweb/bilder/" to just "bilder/" 
here is the edited file this should work :D
[reddit.zip](https://github.com/Fredwuz/venom-bot-WhatsappWebBot/files/5022266/reddit.zip)

just unzip the file and replace your reddit.js with it

**Comment by xaryow** [comment]
Ok thanks for the solutions sir <3
