### ISSUE TITLE
problem with image to sticker

### ISSUE THREAD

**Issue by autorunexe** [Fredwuz/venom-bot-WhatsappWebBot#2]
nothing happen when i try to use image to sticker also in terminal not show anything, can you explain to me how to use that?

**Comment by Fredwuz** [comment]
What are you sending the Bot are you sending it your image + Sticker as caption?

**Comment by Fredwuz** [comment]
![image](https://user-images.githubusercontent.com/36505101/89302387-0d3a7100-d66b-11ea-971d-d8ac27dc2fa9.png)
it should look like this the sticker sending back can take sometime because is editing the image to fit 1:1 format

**Comment by autorunexe** [comment]
> ![image](https://user-images.githubusercontent.com/36505101/89302387-0d3a7100-d66b-11ea-971d-d8ac27dc2fa9.png)
> it should look like this the sticker sending back can take sometime because is editing the image to fit 1:1 format

already put a "sticker" as a caption but nothing happened.

**Comment by Fredwuz** [comment]
can you try to run the sendSticker.js with node like "node sendSticker.js" and if there is any error post it

**Comment by xaryow** [comment]
i also found a problem with sticker this error show on terminal:

(node:31015) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/home/admin/nom/Sticker/62851553696971@c.us.png'
    at Object.openSync (fs.js:462:3)
    at syncFileToBuffer (/home/admin/nom/node_modules/image-size/dist/index.js:71:27)
    at imageSize (/home/admin/nom/node_modules/image-size/dist/index.js:101:24)
    at Object.exports.sendSticker (/home/admin/nom/Scripts/sendSticker.js:19:28)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:31015) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:31015) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

but when i already create new folder named "Sticker" everything works fine.

**Comment by Fredwuz** [comment]
Do you mean when you create the Sticker folder everything works also sending the sticker or just no error?

**Comment by xaryow** [comment]
> Do you mean when you create the Sticker folder everything works also sending the sticker or just no error?

when i create the folder everything works and not show any error.

**Comment by Fredwuz** [comment]
ohh ok yeah 😅 will add this to the Readme to create the folders :D

**Comment by Fredwuz** [comment]
does the sendSticker function work after that?
