### ISSUE TITLE
Nhentai downloader not working on certain doujinshi

### ISSUE THREAD

**Issue by InushaDeSilva** [Fredwuz/venom-bot-WhatsappWebBot#9]
well...............................

internal/streams/legacy.js:61
      throw er; // Unhandled stream error in pipe.
      ^

[Error: ENOENT: no such file or directory, open 'C:\Users\DELL\Desktop\Whatsapp-Botto UwU\nhentai\[666Protect (Jingrock)] Otouto no Musume 4 -Saishuushou- | 弟弟的女兒4 -最終章- [Chinese] [就變態翻譯組一人樣 x 我尻故我在個人漢化] [Digital]0.jpg'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\DELL\\Desktop\\Whatsapp-Botto UwU\\nhentai\\[666Protect (Jingrock)] Otouto no Musume 4 -Saishuushou- | 弟弟的女兒4 -最終章- [Chinese] [就變態翻譯組 一人樣 x 我尻故我在個人漢化] [Digital]0.jpg'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! whatsapp-botto-re@3.0.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the whatsapp-botto-re@3.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\DELL\AppData\Roaming\npm-cache\_logs\2021-01-16T20_18_02_350Z-debug.log

**Comment by Fredwuz** [comment]
can you send me the nhentai code you are trying to download and the code of the module you are using

**Comment by Fredwuz** [comment]
i've updated nhentai api to nhentai now it should work
